### ISSUE TITLE
JGROUPSPING table is not created for Oracle

### ISSUE THREAD

**Issue by bjagg** [Jasig/uPortal#1401]
**Describe the bug**
JGROUPSPING table is not created when using an Oracle database.

**To Reproduce**
1. Set up an Oracle database
2. Configure uPortal-start to use Oracle database
3. `./gradlew clean portalInit portalOpen`
4. Look for `JGROUPSPING` table

**Expected behavior**
`JGROUPSPING` table exists in the Oracle database.

**Stacktrace**
The Catalina log file has these errors:
08-Nov-2018 13:59:51.877 SEVERE [localhost-startStop-2] org.jgroups.protocols.JDBC_PING.delete JGRP000145: Error updating JDBC_PING table
java.sql.SQLSyntaxErrorException: ORA-00942: table or view does not exist

**Platform:**
 - uPortal Version: uPortal 5
 - Database: Oracle

**Additional context**
https://github.com/Jasig/uPortal/blob/master/uPortal-webapp/src/main/resources/properties/db/tables.xml#L431

**Comment by mairi** [comment]
@bjagg Ah!  I saw errors in the log relating to this & had parked it to look at later - since I can reproduce, happy to help investigate/test/otherwise feed into this one.

**Comment by mairi** [comment]
@bjagg I just went to have a look at the tables in our Oracle Dev instance & am seeing something odd.  I definitely had errors in the catalina.out log about missing JGROUPSPING table, but now that I look in the database I can see that table has been created.  I've run portalInit more than once against that instance, so it looks as though the problem resolved itself, although I don't quite understand how!

**Comment by asgrant** [comment]
@bjagg if it is any help, we are seeing something similar with a PostgreSQL database. I've found that I can replicate this error this way...

delete the existing uportal database and recreate it (drop database uportal5 / create database uportal5 owner up5admin)

Then with uportal-start: ./gradlew build dataInit

It will give me a series of these errors with the jgroupsping. Now once uPortal starts, this error seems to go away on another dataInit, however on a fresh database I can always replicate.
```
[ant:java] Nov 09, 2018 10:31:51 AM org.jgroups.protocols.JDBC_PING contains
[ant:java] SEVERE: JGRP000141: Error reading table
[ant:java] org.postgresql.util.PSQLException: ERROR: relation "jgroupsping" does not exist
[ant:java]   Position: 44
[ant:java]      at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2477)
[ant:java]      at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2190)
[ant:java]      at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:300)
[ant:java]      at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:428)
[ant:java]      at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:354)
[ant:java]      at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:169)
[ant:java]      at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:117)
[ant:java]      at org.jgroups.protocols.JDBC_PING.contains(JDBC_PING.java:229)
[ant:java]      at org.jgroups.protocols.JDBC_PING$InfoWriter.run(JDBC_PING.java:513)
[ant:java]      at org.jgroups.util.TimeScheduler3$Task.run(TimeScheduler3.java:291)
[ant:java]      at org.jgroups.util.TimeScheduler3$RecurringTask.run(TimeScheduler3.java:325)
[ant:java]      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[ant:java]      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[ant:java]      at java.lang.Thread.run(Thread.java:745)
```

**Comment by drewwills** [comment]
Thanks very much for looking into this issue folks.  We're having trouble with `jgroupsping` at State Center too.

**Comment by mairi** [comment]
Interesting @drewwills!  @asgrant's experience explains why after a second portalInit the problem is gone.  We don't recreate the schema each time we initialise.  I did wonder if it was something to do with the VARBINARY column on the table, not sure if that would pose problem for both Oracle & SQL Server. The only other thing of note is that it's the only table with sinceMajor of '5'...could that be relevant?
