### ISSUE TITLE
Statistics portlet fails to create visualization

### ISSUE THREAD

**Issue by cbeach47** [Jasig/uPortal#2252]
**Describe the bug**
Statistics portlet fails to create visualization due to stack trace ( see below)

**To Reproduce**
1. Boot up uP 5.8.3-SNAPSHOT
2. Add `Statistics` portlet
3. Try to run the following:
![image](https://user-images.githubusercontent.com/28629296/104389916-2856ba00-5502-11eb-917f-7be65cb22ebe.png)

**Expected behavior**
The statistics portlet visualization should work

**Stacktrace**
```Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Joda date/time type `org.joda.time.DateMidnight` not supported by default: add Module "com.fasterxml.jackson.datatype:jackson-datatype-joda" to enable handling (through reference chain: java.util.HashMap["reportRequest"]->org.apereo.portal.portlets.statistics.TabRenderReportForm["start"])
	at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:77)
	at com.fasterxml.jackson.databind.SerializerProvider.reportBadDefinition(SerializerProvider.java:1276)
	at com.fasterxml.jackson.databind.ser.impl.UnsupportedTypeSerializer.serialize(UnsupportedTypeSerializer.java:35)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:728)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:770)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeFields(MapSerializer.java:808)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeWithoutTypeInfo(MapSerializer.java:764)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:720)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:35)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
	at com.fasterxml.jackson.databind.ObjectWriter$Prefetch.serialize(ObjectWriter.java:1514)
	at com.fasterxml.jackson.databind.ObjectWriter.writeValue(ObjectWriter.java:1006)
	at org.springframework.web.servlet.view.json.AbstractJackson2View.writeContent(AbstractJackson2View.java:211)
	at org.springframework.web.servlet.view.json.AbstractJackson2View.renderMergedOutputModel(AbstractJackson2View.java:160)
	at org.springframework.web.servlet.view.AbstractView.render(AbstractView.java:304)
	at org.springframework.web.servlet.ViewRendererServlet.renderView(ViewRendererServlet.java:114)
	at org.springframework.web.servlet.ViewRendererServlet.processRequest(ViewRendererServlet.java:86)
	at org.springframework.web.servlet.ViewRendererServlet.doPost(ViewRendererServlet.java:73)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:728)
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:470)
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:395)
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:316)
	at org.apache.pluto.container.impl.PortletRequestDispatcherImpl.doDispatch(PortletRequestDispatcherImpl.java:169)
	at org.apache.pluto.container.impl.PortletRequestDispatcherImpl.forward(PortletRequestDispatcherImpl.java:217)
	at org.springframework.web.portlet.ForwardingDispatcherPortlet.doRender(ForwardingDispatcherPortlet.java:50)
	at org.springframework.web.portlet.DispatcherPortlet.render(DispatcherPortlet.java:1126)
	at org.springframework.web.portlet.DispatcherPortlet.doResourceService(DispatcherPortlet.java:876)
	at org.springframework.web.portlet.FrameworkPortlet.processRequest(FrameworkPortlet.java:540)
	at org.springframework.web.portlet.FrameworkPortlet.serveResource(FrameworkPortlet.java:490)
	at org.apereo.portal.portlet.container.FilterChainImpl.doFilter(FilterChainImpl.java:206)
	at org.apereo.portal.portlet.container.FilterChainImpl.processFilter(FilterChainImpl.java:77)
	at org.apereo.portal.portlet.container.FilterManagerImpl.processFilter(FilterManagerImpl.java:103)
	at org.apache.pluto.container.driver.PortletServlet.dispatch(PortletServlet.java:350)
	at org.apache.pluto.container.driver.PortletServlet.doPost(PortletServlet.java:267)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:728)
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:470)
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:395)
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:316)
	at org.apache.pluto.driver.container.DefaultPortletInvokerService.invoke(DefaultPortletInvokerService.java:229)
	at org.apache.pluto.driver.container.DefaultPortletInvokerService.serveResource(DefaultPortletInvokerService.java:149)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:84)
	at org.apereo.portal.portlet.dao.jpa.ThreadContextClassLoaderAspect.doThreadContextClassLoaderUpdate(ThreadContextClassLoaderAspect.java:63)
	at sun.reflect.GeneratedMethodAccessor251.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:627)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:616)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
	at com.sun.proxy.$Proxy453.serveResource(Unknown Source)
	at org.apache.pluto.container.impl.PortletContainerImpl.doServeResource(PortletContainerImpl.java:203)
	at org.apereo.portal.portlet.rendering.PortletRendererImpl.doServeResource(PortletRendererImpl.java:684)
	... 9 common frames omitted
```

**Platform:**
 - uPortal Version: [e.g. head of master on 2021/1/12
 - OS: Ubuntu
 - Browser Firefox

**Comment by ChristianMurphy** [comment]
![Screenshot_2021-01-12 Statistics uPortal by Apereo(1)](https://user-images.githubusercontent.com/3107513/104391138-7cf73680-54fc-11eb-9e0e-ecc972f6bdd7.png)

I'm able to get tab renders report to display, in my testing
`Generate a new Portlets Moved to Layouts Report`, `Generate a new Portlets Deleted from Layouts Report`, and `Generate a new Portlets Added to Layouts Report` are missing the interval field, and the report cannot generate without a value

**Comment by cbeach47** [comment]
While some of the 5.8.2 chart configs have those missing fields that block the report submission, `Concurrent Users` does show the visualization.

**Comment by cbeach47** [comment]
Might have had something to do with #2157

**Comment by bjagg** [comment]
@cbeach47 I think this has been resolved with #2157 and another PR in 5.10.0
